### PR TITLE
Text-based Discover Lens cleanup

### PR DESCRIPTION
**Pull request by davismcphee**
A few suggestions I think could help cleanup the Unified Histogram text-based work:
- [Make text based total hits state internal to Unified Histogram](https://github.com/stratoula/kibana/commit/6b82e9c4fb9948fff63041d905752400ba0c0c71)
- [Call timefilter.getAbsoluteTime to get timeRange](https://github.com/stratoula/kibana/commit/ebd2288f32b49cbb23e0340e3fd9f0d35e211c9c)
- [Revert changes to use_lens_props to respect refetch$](https://github.com/stratoula/kibana/commit/10d70f3800e0a4bbb438406949b76e5f112e99c2)

### CODE REVIEW

**Comment by stratoula** [comment]
@davismcphee thanx for the cleanup here. I see 2 problems:
- The hits sometimes is not updated

esql

- The chart selector doesn't work (you also mention this)

**Comment by stratoula** [comment]
@davismcphee this works great! There is only one problem. If I select a field to the dataview mode and go to text based, then it displays the chart while it should not.

esql

I fixed that on my PR https://github.com/elastic/kibana/pull/151581/commits/ff9de56a53066aa4160ba64d7d0ccb075f9fbabd but the same fix doesn't work here.

**Comment by davismcphee** [comment]
@stratoula Thanks for the heads up! I still have a bit of work left on this before before it's ready to merge -- although I'm getting close now. It's definitely complicated to get everything working as expected, but we'll get there soon.

I also haven't merged the latest changes from your branch with the fix, which might partly explain what you're seeing. And I broke some tests and types that I'll need to fix too 😅.

I'm going to convert this back to a draft for now until I think things are working as expected, then I'll republish the PR for review.

**Comment by stratoula** [comment]
oh thanx Davis :D I really appreciate your effort here! Ping me when you need a testing hand!

**Comment by davismcphee** [comment]
@stratoula This PR should be ready for testing again. I tried to get rid of all unnecessary refetches, and it's not perfect but should be good for technical preview. Longer term I think we'll need to rethink how we're handling some of the text-based languages work in Discover because the state is pretty complicated to manage.

I didn't get a chance to write as many tests as I hoped for the changes, but that can be followup work depending on the urgency. I'm also going to plan for some functional tests in Discover to track refetches and make future changes here easier to test.

I also included a fix for a multiple refetch issue in the Lens embeddable that I have an open PR for here so it was easier to test: https://github.com/elastic/kibana/pull/153517.

And I created a draft PR from this branch against the main repo to make sure it passes CI before merging into your branch (currently still running the build): https://github.com/elastic/kibana/pull/153415.

**Comment by stratoula** [comment]
Wow @davismcphee thanx for all your effort and for creating a new PR for the CI to run! I will start testing and let you know!
Ahhh, I updated your temp PR with main and this was also reflected here 😬 and now we see 941 files difference 🤕 I don't get why though 🤔

**Comment by stratoula** [comment]
This looks fantastic! I tested it in Chrome and I cant find any regression. Possibly if you re-create the PR this 941 files difference will disappear and we will be able to merge it to my branch!

**Pull request merged**
